spring:
  application:
    name: pdsa-backend
  datasource:
    url: jdbc:sqlite:../database/pdsa_game_system.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/migration/V1__init_sqlite_schema.sql
        - classpath:db/migration/V3__add_algorithm_solution_answers.sql
server:
  port: 8080
